### ISSUE TITLE
İyzipay Boş sayfa hatası

### ISSUE THREAD

**Issue by rooteto** [4bitweb/whmcs-iyzipay-tokenized#4]
Merhaba,

Öncelikle eklenti için teşekkür ederim.

WHMCS 7 sürümünü kullanıyorum, PHP sürümüm ise 5.6.26.

Dosyaları indirip gateway klasörüne ekledim. Ödeme yöntemlerinden aktifleştirip gereken bilgileri eksiksiz girdim.

Test fatura oluşturup ödeme denedim. Kredi kartı ekranı geldi bilgileri girdim ancak beyaz sayfada kalıyor site. Devam etmiyor. "HTTP ERROR 500" hatası alıyorum.

**Comment by canozokur** [comment]
selam!

WHMCS'nin gateway loglarinda veya PHP'nin error loglarinda bir problem gozukuyor mu? 500 PHP tarafindaki bir hatayi isaret ediyor gibi. WHMCS 7 ve PHP 5.6'da ben de test edeyim.

**Comment by canozokur** [comment]
bu hatayi kendi test ortamimda tekrarlayamadim, sizde hala problem suruyor mu?

**Comment by canozokur** [comment]
daha fazla bilgi alamadigim icin kapatiyorum.
